version: "3.3"
services:
  api:
    build: .
    container_name: app
    command: bash -c "pip install pipenv && pipenv install --system && DEBUG=True python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
